name: Deploy Documentation

on:
  push:
    branches:
      - main  # Or any branch where your source files are located
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Sphinx
      run: pip install sphinx sphinx-rtd-theme rst2pdf bs4

    - name: Build Documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.AFFDOWS_PAT }}  # Uses GitHub's default token
        publish_branch: gh-pages  # Deploy to the gh-pages branch
        publish_dir: ./docs/_build/html  # The directory where HTML files are generated
        allow_empty_commit: true

