name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Sphinx
      run: pip install sphinx sphinx-rtd-theme rst2pdf bs4

    - name: Build Documentation
      run: |
        cd docs
        make html

    - name: Check if HTML build directory exists
      run: |
        if [ -d "docs/_build/html" ]; then
          echo "HTML build directory exists"
        else
          echo "HTML build directory does not exist"
          exit 1
        fi

    - name: Deploy to GitHub Pages
      env:
        # Use the PAT stored in GitHub Secrets
        GH_PAT: ${{ secrets.AFFDOWS_PAT }}
      run: |
        git fetch origin gh-pages
        git checkout -f gh-pages
        git branch
        # Clean up old files from the gh-pages branch

        ls -l ./

        # Copy the new files from the Sphinx build
        cp -r ./docs/_build/html/* .
        cp -r ./docs/_build/html/.* .
        ls -l .

        # Configure Git for commit
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Commit and push the changes to gh-pages branch
        git add .
        git commit -m "Deploy documentation to gh-pages"
        git push https://x-access-token:${{ secrets.AFFDOWS_PAT }}@github.com/${{ github.repository }} gh-pages

